# Generated by Django 3.2.7 on 2022-11-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeBerry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Ягода')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Ягода',
                'verbose_name_plural': 'Ягоды',
            },
        ),
        migrations.CreateModel(
            name='CakeDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Декор')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Декор',
                'verbose_name_plural': 'Декоры',
            },
        ),
        migrations.CreateModel(
            name='CakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Форма торта')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Форма торта',
                'verbose_name_plural': 'Формы тортов',
            },
        ),
        migrations.CreateModel(
            name='CakeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1, verbose_name='Количество уровней')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Размер торта',
                'verbose_name_plural': 'Размеры тортов',
            },
        ),
        migrations.CreateModel(
            name='CakeTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Топпинг')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Топпинг',
                'verbose_name_plural': 'Топпинги',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'Оплачен'), (2, 'Завершён')], db_index=True, default=0, verbose_name='Статус')),
                ('cake_caption', models.CharField(max_length=200, verbose_name='Надпись')),
                ('order_comment', models.TextField(verbose_name='Комментарий к заказу')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки')),
                ('delivery_comment', models.TextField(verbose_name='Комментарий для курьера')),
                ('total_cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость заказа')),
                ('cake_berry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cakes.cakeberry', verbose_name='Ягоды')),
                ('cake_decor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cakes.cakedecor', verbose_name='Декор')),
                ('cake_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cakes.cakeform', verbose_name='Форма торта')),
                ('cake_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cakes.cakesize', verbose_name='Количество уровней')),
                ('cake_topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cakes.caketopping', verbose_name='Топпинг')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cakes.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
