# Generated by Django 3.2.7 on 2022-11-23 08:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_auto_20221123_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Телефон'),
        ),
    ]
