# Generated by Django 3.2.7 on 2022-11-28 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_promodod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocod', models.CharField(max_length=20, verbose_name='Промокод')),
                ('discount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Скидка в процентах %')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': '      Промокоды',
            },
        ),
        migrations.DeleteModel(
            name='Promodod',
        ),
    ]
